USE [master]
GO
CREATE LOGIN [MarCo] WITH PASSWORD=N'MarCo', DEFAULT_DATABASE=[MarCo], CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO

USE [MarCo]
GO
CREATE USER [MarCo] FOR LOGIN [MarCo]
GO
USE [MarCo]
GO
ALTER ROLE [db_owner] ADD MEMBER [MarCo]
GO